### ISSUE TITLE
Improve the Drag & Drop UI

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#161]
**Current situation :**

1. The drop targets get different colors when hovered.
2. There is no clear drag handle.

**Sub-tasks that need to be performed :**

- [x] Add a drag handle.
- [x] Display a nicer indicator where the content is about to be dropped.
- [ ] Hide the currently dragged element.
