### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#181]
## To-do

- [x] **Web :** Login and registration errors are not clear.
- [x] **Web :** Questions should probably be created at the start of the list.

## Web frontend

- [x] The default question visibility should maybe not be hidden.
- [x] **Web :** We can't easily find out that question order can be modified.
- [ ] The "new question" button is a bit lost on large screens.
- [ ] When editing or creating content, the focus is sometimes not properly set.
- [x] On slow networks, there are sometimes no "loading" states.
- [x] Some terms are not really clear.
  + Create -> **Confirm** (better)
  + Cancel -> **Discard** (better)
  + Modify -> **Save** (better)

## Mobile frontend

- [x] The back button does not work.
- [x] **Mobile :** How do we know if a poll has ended ?

**Comment by alexandrepiveteau** [comment]
## Context

The users were asked to "create a poll for a participant, and ask the participant to answer at least 3 questions". No indications were given as to how to use the app.

**Comment by alexandrepiveteau** [comment]
@matt989253 we've addressed or ignored all the points listed here. I'm closing the issue.
