### ISSUE TITLE
Close the navigation destinations on navigation

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#61]
**Current situation :**

1. The main destinations are displayed in the navigation menu.
2. When the destination is changed, the menu remains open.

**Sub-tasks that need to be performed :**

- [x] Add a dedicated message for navigation requests of the navigation bar.
- [x] Ensure that the navigation request closes the bar.
- [x] Navigate once the navigation request has been received.

**Comment by alexandrepiveteau** [comment]
Fixed in #63.
