### ISSUE TITLE
Catch the right error message while logging in

### ISSUE THREAD

**Issue by matt989253** [heig-PRO-b04/elm-frontend#69]
**Current situation :**

1. When logging in and specifying an incorrect username and password combination, a network error is detected when in reality, it is a bad credentials error that is wrongly displayed
2. This was not the case before

**Sub-tasks that need to be performed :**

- [x] Verify if the problem comes from the frontend or the backend
- [x] If the problem comes from the frontend, catch the right error and display the correct message
- [x] If the problem comes from the backend, open a similar issue on the backend repo

**Comment by alexandrepiveteau** [comment]
The frontend checks for the error code `403`, but the server issues the error code `400`.

- [Frontend](https://github.com/heig-PRO-b04/elm-frontend/blob/master/src/Api.elm#L242-L243) (at commit 111e80a).
- [Backend](https://github.com/heig-PRO-b04/java-backend/blob/master/src/main/java/ch/heigvd/pro/b04/auth/exceptions/LoginControllerExceptionHandler.java#L13-L16) (at commit 5ef0b78).

**Comment by alexandrepiveteau** [comment]
HTTP error handling will soon be reworked in the backend, and the final error code will probably be decided at that time.
