### ISSUE TITLE
Implement a Viewer for logged in users

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#72]
**Current situation :**

1. A user that's logged in or not is represented in a `Session`.
2. We don't have any types to represent users that are known to be logged in.

**Sub-tasks that need to be performed :**

- [x] Implement a `Viewer` type that represents logged in users.
- [x] Offer a `Session -> Maybe Viewer` converter.
- [x] Change the `Page.Polls` to use a `Viewer` as its init type.
