### ISSUE TITLE
Implement poll deletion

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#74]
**Current situation :**

1. Polls are listed in the polls page.
2. Polls may not be deleted.

**Sub-tasks that need to be performed :**

- [x] Implement the endpoint to delete polls in the Api.
- [x] Delete polls on delete button clicks.
- [x] Reload the poll page content whenever a deletion occurs.
