### ISSUE TITLE
Add a dedicated page for credentials errors

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#83]
**Current situation :**

1. Users might get disconnected when their credentials expire.
2. The user is not informed that something went badly, and simply sees no content displayed.

**Sub-tasks that need to be performed :**

- [x] Add a new page for connection issues.
- [x] Display on the page some info that tells the user that they are disconnected.
- [x] Direct the user (automatically, after a few seconds ?) to the login page.
