### ISSUE TITLE
Add some automated tests

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#85]
**Current situation :**

1. There are no unit tests in the app.

**Sub-tasks that need to be performed :**

- [ ] Identify what makes sense to be tested.
- [ ] Add some unit tests.
- [ ] Add some integration tests. We might make use of the [elm-program-test](https://package.elm-lang.org/packages/avh4/elm-program-test/latest/) package (assuming it's even what we're looking for).

**Comment by alexandrepiveteau** [comment]
It looks like elm-program-test would require some pretty major refactorings of our application. Therefore, I think this might be something we dismiss.
