### ISSUE TITLE
Persist the authentication token

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/elm-frontend#87]
**Current situation :**

1. The authentication token is retrieved on registration or login.
2. The token is lost when the user exits the page, or refreshes it.

**Sub-tasks that need to be performed :**

- [x] See how we can use browser storage for the token.
- [x] Persist the authentication token and moderator identifier on Api requests.
- [x] Retrieve the Api tokens on the page launch (or later if they're updated).
